const shell=(title,body,script)=>`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · DataFoldIT Test</title><link rel="stylesheet" href="/poc.css"><main><header><strong>DATAFOLDIT</strong><span>Test workspace</span></header><h1>${title}</h1>${body}<p id="message" role="status"></p></main><script src="${script}" defer></script></html>`;
export const loginPage=shell('Welcome',`<p>Use your approved email. New users must verify their email before creating a password.</p><form id="email-step"><label>Email<input name="email" type="email" autocomplete="username" required></label><button>Continue</button></form><form id="password-step" hidden><p id="selected-email"></p><label>Password<input name="password" type="password" autocomplete="current-password" required></label><label>Authenticator code (only if enabled)<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}"></label><button>Sign in</button><button type="button" id="setup">First time? Email me a setup link</button></form>`, '/login.js');
const sendJs=`async function send(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to complete request');return data;}const message=document.querySelector('#message');`;
export const loginJs=sendJs+`
let email='';
document.querySelector('#email-step').addEventListener('submit',e=>{e.preventDefault();email=e.target.elements.email.value.trim();document.querySelector('#selected-email').textContent=email;e.target.hidden=true;document.querySelector('#password-step').hidden=false;});
document.querySelector('#password-step').addEventListener('submit',async e=>{e.preventDefault();try{await send('/api/login',{email,...Object.fromEntries(new FormData(e.target))});location.href='/';}catch(err){message.textContent=err.message;}});
document.querySelector('#setup').addEventListener('click',async e=>{e.target.disabled=true;try{await send('/api/access/request',{email});message.textContent='If this email is approved and not already registered, a private setup link will be sent. Check your inbox and spam folder.';}catch(err){message.textContent=err.message;}finally{e.target.disabled=false;}});
`;
export const setupPage=shell('Create your account',`<p>Your private email link verifies your approved address.</p><form id="enroll" hidden><p id="approved-email"></p><label>New password<input name="password" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><label>Confirm password<input name="confirm" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><label id="choice">Authenticator protection<select name="mfa"><option value="yes">Set up MFA (recommended)</option><option value="no">Skip for now</option></select></label><p id="admin-note" hidden>MFA is required for the administrator account.</p><section id="mfa-setup"><p>Scan this private QR code with Zoho OneAuth or another authenticator.</p><img id="qr" alt="Private authenticator enrollment QR code" width="260" height="260"><p><a id="auth-link">Open authenticator on this device</a></p><label>Six-digit authenticator code<input name="code" inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code" required></label></section><button>Create account</button></form><a href="/">Back to sign in</a>`, '/enrollment.js');
export const setupJs=sendJs+`
const form=document.querySelector('#enroll'),token=new URLSearchParams(location.hash.slice(1)).get('token');history.replaceState(null,'','/accept');let required=true;
async function start(){const data=await send('/api/enrollment/begin',{token});required=data.mfaRequired;document.querySelector('#approved-email').textContent='Verified email: '+data.email;document.querySelector('#qr').src=data.qr;document.querySelector('#auth-link').href=data.otpauth;document.querySelector('#choice').hidden=required;document.querySelector('#admin-note').hidden=!required;form.hidden=false;message.textContent='Use at least 12 characters. Keep your QR code private.';}
start().catch(e=>message.textContent=e.message);
form.elements.mfa.addEventListener('change',()=>{const skip=!required&&form.elements.mfa.value==='no';document.querySelector('#mfa-setup').hidden=skip;form.elements.code.required=!skip;});
form.addEventListener('submit',async e=>{e.preventDefault();const fields=Object.fromEntries(new FormData(form));if(fields.password!==fields.confirm){message.textContent='Passwords do not match.';return;}const button=form.querySelector('button');button.disabled=true;try{await send('/api/enrollment/accept',{token,password:fields.password,code:fields.code,skipMfa:!required&&fields.mfa==='no'});form.reset();form.hidden=true;document.querySelector('#qr').removeAttribute('src');document.querySelector('#auth-link').removeAttribute('href');message.textContent='Account created. Return to sign in. If you enabled MFA, wait for the next new authenticator code.';}catch(err){message.textContent=err.message;}finally{button.disabled=false;}});
`;
export const usersPage=csrf=>shell('User access',`<a href="/">Back to workspace</a><p>Approve each employee by email and choose read-only or read/write access. They receive a private verification link and create their own password. MFA is optional for employees and required for admins.</p><form id="invite"><label>Email<input name="email" type="email" maxlength="254" required></label><label>Access<select name="role"><option value="read">Read only</option><option value="write">Read/write</option></select></label><button>Approve and send setup email</button></form><h2>Enrolled users</h2><div id="users"></div><input id="csrf" type="hidden" value="${csrf}">`, '/admin.js');
export const usersJs=`const message=document.querySelector('#message');document.querySelector('#invite').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const r=await fetch('/api/admin/invitations',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':document.querySelector('#csrf').value},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});const data=await r.json();if(!r.ok)throw new Error(data.error);message.textContent=data.emailSent?'Approved. Zoho accepted the setup email for delivery. Ask the employee to check their inbox.':'Approved, but email could not be sent. Check email settings and retry.';}catch(err){message.textContent=err.message;}finally{button.disabled=false;}});fetch('/api/admin/users').then(async r=>{if(!r.ok)throw new Error('Cannot load users');return r.json();}).then(rows=>{const table=document.createElement('table');for(const row of rows){const tr=document.createElement('tr');for(const value of [row.email,row.role,row.active?'Enabled':'Disabled']){const td=document.createElement('td');td.textContent=value;tr.append(td);}table.append(tr);}document.querySelector('#users').replaceChildren(table);}).catch(e=>message.textContent=e.message);`;
