export const enrollmentPage=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Set up access · DataFoldIT Test</title><link rel="stylesheet" href="/poc.css"><main><header><strong>DATAFOLDIT</strong><span>Test workspace</span></header><h1>Set up your account</h1><p id="message" role="status">Checking your invitation…</p><form id="enroll" hidden><p id="approved-email"></p><label>Create password<input name="password" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><label>Confirm password<input name="confirm" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><h2>Set up your authenticator</h2><p>In Zoho OneAuth or another authenticator, add an account by scanning this QR code. Keep this code private.</p><img id="qr" alt="Your private authenticator setup QR code" width="260" height="260"><p><a id="auth-link">Open authenticator on this device</a></p><label>Enter its six-digit code<input name="code" inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code" required></label><button>Create account</button></form><p><a href="/">Back to sign in</a></p></main><script src="/enrollment.js" defer></script></html>`;
export const enrollmentJs=`
const status=document.querySelector('#message'),form=document.querySelector('#enroll');
const token=new URLSearchParams(location.hash.slice(1)).get('token');
history.replaceState(null,'','/accept');
async function post(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw new Error(result.error||'Unable to complete setup');return result;}
async function start(){const data=await post('/api/enrollment/begin',{token});document.querySelector('#approved-email').textContent='Approved email: '+data.email;document.querySelector('#qr').src=data.qr;document.querySelector('#auth-link').href=data.otpauth;form.hidden=false;status.textContent='Use at least 12 characters for your password. This invitation expires after 24 hours.';}
start().catch(e=>status.textContent=e.message);
form.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));if(data.password!==data.confirm){status.textContent='Passwords do not match.';return;}const button=form.querySelector('button');button.disabled=true;try{await post('/api/enrollment/accept',{token,password:data.password,code:data.code});form.reset();form.hidden=true;document.querySelector('#qr').removeAttribute('src');document.querySelector('#auth-link').removeAttribute('href');status.textContent='Account created. Go back to sign in with your password and the next new authenticator code.';}catch(e){status.textContent=e.message;}finally{button.disabled=false;}});
`;
export const adminPage=csrf=>`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Users · DataFoldIT Test</title><link rel="stylesheet" href="/poc.css"><main><header><strong>DATAFOLDIT</strong><a href="/">Back to workspace</a></header><h1>User access</h1><p>Approve an email and choose its access level. Setup requires a personal password and authenticator.</p><form id="invite"><label>Email<input type="email" name="email" maxlength="254" required></label><label>Access<select name="role"><option value="read">Read only</option><option value="write">Read/write</option></select></label><button>Create invitation</button></form><p>Email delivery is not connected on this hosted test yet. Creating an invitation does not send email. Share its private setup link directly with that employee.</p><p id="message" role="status"></p><a id="invite-link" hidden>Private setup link</a><h2>Enrolled users</h2><div id="users"></div><input id="csrf" type="hidden" value="${csrf}"></main><script src="/admin.js" defer></script></html>`;
export const adminJs=`
const message=document.querySelector('#message');
document.querySelector('#invite').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;const link=document.querySelector('#invite-link');link.hidden=true;link.removeAttribute('href');try{const r=await fetch('/api/admin/invitations',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':document.querySelector('#csrf').value},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});const result=await r.json();if(!r.ok)throw new Error(result.error);link.href=result.url;link.textContent=result.url;link.hidden=false;message.textContent='Invitation created. No email sent. Share this link only with '+result.email+'. Creating another invitation invalidates the earlier link.';}catch(e){message.textContent=e.message;}finally{button.disabled=false;}});
fetch('/api/admin/users').then(async r=>{if(!r.ok)throw new Error('Cannot load users');return r.json();}).then(rows=>{const table=document.createElement('table');for(const row of rows){const tr=document.createElement('tr');for(const value of [row.email,row.role,row.active?'Enabled':'Disabled']){const td=document.createElement('td');td.textContent=value;tr.append(td);}table.append(tr);}document.querySelector('#users').replaceChildren(table);}).catch(e=>message.textContent=e.message);
`;
