import ExcelJS from 'exceljs';
export async function exportWorkbook(rows,fields,{period='all',month='',day='',tab='all',from='',to=''}={}){
 if(!['all','monthly','daily','custom'].includes(period)||tab!=='all'&&!Object.hasOwn(fields,tab))throw Error('Invalid report selection');
 if(period==='monthly'&&!/^\d{4}-\d{2}$/.test(month)||period==='daily'&&!/^\d{4}-\d{2}-\d{2}$/.test(day))throw Error('Choose a valid reporting period');
 const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!isNaN(new Date(value))&&new Date(value).toISOString().slice(0,10)===value;
 if(period==='custom'&&(!validDate(from)||!validDate(to)||from>to))throw Error('Choose valid From and To dates; From must be on or before To.');
 if(tab!=='all'){fields={[tab]:fields[tab]};rows=rows.filter(r=>r.kind===tab);}
 if(fields.payroll){const visible={};for(const [key,type] of Object.entries(fields.payroll)){if(['pct','commission','tax_breakdown','job_start','job_end','effective_end'].includes(key))continue;visible[key==='effective_start'?'effective_date_range':key]=key==='effective_start'?'text':type;}fields={...fields,payroll:visible};}
 rows=rows.map(r=>r.kind==='payroll'?{...r,data:{...r.data,effective_date_range:r.data.effective_date_range||(r.data.effective_start&&r.data.effective_end?r.data.effective_start+' to '+r.data.effective_end:'')}}:r);
 const book=new ExcelJS.Workbook();book.creator='DataFoldIT test';
 const scope=rows.filter(r=>{const date=r.data.date||r.data.month||'';if(period==='custom'){if(r.kind==='payroll'){if(r.data.effective_start&&r.data.effective_end)return r.data.effective_start<=to&&r.data.effective_end>=from;const payrollMonth=r.data.month||'';return !!payrollMonth&&payrollMonth>=from.slice(0,7)&&payrollMonth<=to.slice(0,7);}return !!date&&date>=from&&date<=to;}return period==='all'||period==='monthly'&&date.slice(0,7)===month||period==='daily'&&(r.kind==='payroll'?date===day.slice(0,7):date===day);});
 const summary=book.addWorksheet('Summary');summary.columns=[{header:'Metric',width:32},{header:'Selected period value',width:25}];summary.addRow(['Period',period==='all'?'All time':period==='monthly'?month:period==='custom'?from+' to '+to:day]);for(const kind of Object.keys(fields)){const selected=scope.filter(r=>r.kind===kind&&(kind!=='invoices'||r.data.status!=='VOID'));const total=selected.reduce((n,r)=>n+Number(r.data[kind==='payroll'?'gross':'amount']||0)*(kind==='bank'&&['Expense','Withdrawal','Transfer Out','Adjustment Out'].includes(r.data.type)?-1:1),0);summary.addRow([kind+' records',selected.length]);summary.addRow([kind==='bank'?'Bank signed total':kind==='payroll'?'Gross payroll':kind+' total',total]);}summary.addRow(['Note','Expenses and bank outflows are separate records; do not add their totals.']);
 for(const kind of Object.keys(fields)){const sheet=book.addWorksheet(kind==='bank'?'Bank Transactions':kind[0].toUpperCase()+kind.slice(1)),keys=[...new Set([...(kind==='invoices'?[]:['tracking_id']),...Object.keys(fields[kind]),'attachment','updated_by'])];sheet.columns=keys.map(key=>({header:key==='tracking_id'?'trnsc_id':key.replaceAll('_',' '),key,width:key==='attachment'?40:20}));
 const selected=scope.filter(r=>r.kind===kind);
 for(const r of selected){const data={...r.data,tracking_id:r.tracking_id||r.data.tracking_id||'',attachment:r.data.attachment||(r.attachments||[]).map(f=>f.name).join(', '),updated_by:r.updated_by};const row=sheet.addRow(data);keys.forEach((key,i)=>{if(fields[kind][key]==='number'){row.getCell(i+1).value=Number(data[key]||0);row.getCell(i+1).numFmt=['hours','pct','commission_pct'].includes(key)?'0.00':'#,##0.00';}});}
 sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,sheet.rowCount),column:keys.length}};sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF142030'}};
 }
 if(period==='custom'&&fields.payroll)summary.addRow(['Payroll date basis','Full records overlapping the effective salary range; payroll month used when no range is recorded. Amounts are not prorated. Credit date is not used.']);
 const data=await book.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([data],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download='datafoldit-test-'+period+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
