import assert from "node:assert/strict";
import {Miniflare} from "miniflare";
import {initializeAuth,provisionUser,totp} from "./auth.mjs";
import {initialize} from "./free-storage.mjs";
import {initializeTransactions} from "./worker.mjs";
import {initializeInvitations} from './invitations.mjs';
import {pendingSchema} from './mfa-settings.mjs';
const origin="https://poc.example.test";
const mail=[];
const runtime=new Miniflare({modules:true,scriptPath:new URL("./worker.mjs",import.meta.url).pathname,compatibilityDate:"2026-08-06",compatibilityFlags:['nodejs_compat'],d1Databases:["DB"],serviceBindings:{MAILER:async request=>{mail.push(await request.json());return new Response('accepted');}}});
const call=(path,init={})=>runtime.dispatchFetch(origin+path,init);
const post=(path,data,cookie="",csrf="",requestOrigin=origin)=>call(path,{method:"POST",headers:{"Content-Type":"application/json",Origin:requestOrigin,Cookie:cookie,"X-CSRF-Token":csrf},body:JSON.stringify(data)});
try{
  const db=await runtime.getD1Database("DB");
  await initializeAuth(db);await initialize(db);await initializeTransactions(db);
  await initializeInvitations(db);
  await db.prepare(pendingSchema).run();
  const secret="3132333435363738393031323334353637383930",password="Synthetic-HTTP-password";
  await provisionUser(db,"writer@example.com",password,"write",secret);
  await provisionUser(db,"reader@example.com",password,"read",secret);
  await provisionUser(db,"admin@example.com",password,"admin",secret);
  assert.equal((await call("/api/transactions")).status,401);
  assert.equal((await call("/")).status,200);
  assert.equal((await post("/api/login",{},"","","https://evil.example")).status,403);
  async function login(email){
    const code=await totp(secret,Math.floor(Date.now()/30000));
    const response=await post("/api/login",{email,password,code});assert.equal(response.status,200);
    const setCookie=response.headers.get("set-cookie");
    assert.match(setCookie,/Secure; HttpOnly; SameSite=Strict/);
    const cookie=setCookie.split(";")[0];
    const page=await (await call("/",{headers:{Cookie:cookie}})).text();
    const csrf=page.match(/id="csrf"[^>]*value="([^"]+)"/)?.[1];
    assert.ok(csrf);return {cookie,csrf};
  }
  const writer=await login("writer@example.com"),reader=await login("reader@example.com");
  const admin=await login('admin@example.com');
  assert.equal((await call('/admin',{headers:{Cookie:reader.cookie}})).status,403);
  assert.equal((await post('/api/admin/invitations',{email:'employee@example.test',role:'write'},writer.cookie,writer.csrf)).status,403);
  assert.equal((await post('/api/admin/invitations',{email:'employee@example.test',role:'write'},admin.cookie,'bad')).status,403);
  const inviteResponse=await post('/api/admin/invitations',{email:'employee@example.test',role:'write'},admin.cookie,admin.csrf);
  assert.equal(inviteResponse.status,201);
  const invite=await inviteResponse.json();assert.equal(invite.emailSent,true);assert.equal(invite.url,undefined);
  const token=new URLSearchParams(new URL(mail.at(-1).link).hash.slice(1)).get('token');
  assert.ok(token);assert.equal((await call('/accept')).status,200);
  assert.equal((await post('/api/enrollment/begin',{token},'','','https://evil.example')).status,403);
  const enrollment=await post('/api/enrollment/begin',{token});assert.equal(enrollment.status,200);
  const setup=await enrollment.json();assert.match(setup.qr,/^data:image\/gif;base64,/);
  const pending=await db.prepare('SELECT mfa_hex FROM poc_invitations WHERE email=?').bind('employee@example.test').first();
  const enrollmentCode=await totp(pending.mfa_hex,Math.floor(Date.now()/30000));
  assert.equal((await post('/api/enrollment/accept',{token,password,code:enrollmentCode})).status,200);
  assert.equal((await post('/api/enrollment/begin',{token})).status,400);
  assert.equal((await post('/api/enrollment/accept',{token,password,code:enrollmentCode})).status,400);
  assert.equal((await db.prepare('SELECT role FROM poc_users WHERE email=?').bind('employee@example.test').first()).role,'write');
  await provisionUser(db,'optional@example.test',password,'read','');
  const optional=await login('optional@example.test');
  const beginLater=await post('/api/security/begin',{password},optional.cookie,optional.csrf);
  assert.equal(beginLater.status,200);
  const pendingMfa=await db.prepare('SELECT secret FROM poc_mfa_pending WHERE user_id=(SELECT id FROM poc_users WHERE email=?)').bind('optional@example.test').first();
  const laterCode=await totp(pendingMfa.secret,Math.floor(Date.now()/30000));
  assert.equal((await post('/api/security/confirm',{code:laterCode},optional.cookie,optional.csrf)).status,200);
  assert.equal((await call('/api/transactions',{headers:{Cookie:optional.cookie}})).status,401);
  assert.equal((await post('/api/login',{email:'optional@example.test',password,code:''})).status,401);
  const tx={description:"Synthetic invoice",amount:"123.45"};
  assert.equal((await post("/api/transactions",tx,reader.cookie,reader.csrf)).status,403);
  assert.equal((await post("/api/transactions",tx,writer.cookie,"forged")).status,403);
  assert.equal((await post("/api/transactions",tx,writer.cookie,writer.csrf)).status,201);
  const rows=await (await call("/api/transactions",{headers:{Cookie:reader.cookie}})).json();
  assert.equal(rows[0].amount_cents,12345);assert.equal(rows[0].updated_by,"writer@example.com");
  const upload=await call("/api/files?name=synthetic.txt",{method:"POST",headers:{Cookie:writer.cookie,Origin:origin,"X-CSRF-Token":writer.csrf,"Content-Length":"6"},body:"sample"});
  assert.equal(upload.status,201);const {id}=await upload.json();
  assert.equal((await call("/api/files/"+id,{headers:{Cookie:reader.cookie}})).status,404);
  const download=await call("/api/files/"+id,{headers:{Cookie:writer.cookie}});
  assert.equal(await download.text(),"sample");assert.match(download.headers.get("Content-Disposition"),/^attachment/);
  assert.equal((await post("/api/logout",{},writer.cookie,writer.csrf)).status,200);
  assert.equal((await call("/api/transactions",{headers:{Cookie:writer.cookie}})).status,401);
  console.log("PASS: actual Worker HTTP login, secure cookies, origin/CSRF rejection, reader write denial, transaction attribution, private attachment and logout.");
  console.log('PASS: admin-only invitation HTTP flow, private QR setup, origin rejection and one-time account activation.');
}finally{await runtime.dispose();}
