import {readTransactions} from './import-reader.mjs';
export function openImport({kind,fields,host,onSaved,targetId=null,initialFile=null,existingRecords=[]}){
 if(host.querySelector('.import-panel'))return;
 const e=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;},panel=e('section');panel.className='import-panel';
 panel.append(e('h2',targetId?'Attach a document':'Import '+kind+' from a document'),e('p',targetId?'The file will be linked to this transaction. This does not extract additional transactions.':'PDF, Word (.docx), PNG/JPG and Excel (.xlsx). Maximum 10 MB, 100 pages and 100 transactions. Review every candidate; extraction is not guaranteed for every layout.'));
 const picker=e('input');picker.type='file';picker.accept='.pdf,.docx,.png,.jpg,.jpeg,.xlsx';picker.setAttribute('aria-label','Select attachment');
 const read=e('button',targetId?'Upload attachment':'Read file'),close=e('button','Cancel'),status=e('p'),preview=e('div');status.setAttribute('role','status');panel.append(picker,read,close,status,preview);host.prepend(panel);let rows=[],file,busy=false;
 close.onclick=()=>{if(!busy)panel.remove();};
 async function send(selected){const data=new FormData();data.append('file',file);data.append('kind',kind);data.append('rows',JSON.stringify(selected));if(targetId)data.append('targetId',targetId);const response=await fetch('/api/import',{method:'POST',headers:{'X-CSRF-Token':document.querySelector('#csrf').value},body:data});const result=await response.json();if(!response.ok)throw Error(result.error||'Import failed');return result;}
 function lock(v){busy=v;picker.disabled=read.disabled=close.disabled=v;}
 async function saved(result){panel.replaceChildren(e('p',targetId?'Attachment uploaded.':result.count+' separate transactions imported.'));try{await onSaved();}catch{panel.append(e('p','Saved successfully, but the list could not refresh. Reload the page; do not import again.'));}}
 read.onclick=async()=>{if(busy)return;file=picker.files[0]||initialFile;if(!file){status.textContent='Choose a file first.';return;}lock(true);preview.replaceChildren();try{if(file.size>10485760)throw Error('Maximum file size is 10 MB.');if(targetId){await saved(await send([]));return;}rows=await readTransactions(file,kind,fields,text=>status.textContent=text);showReview();}catch(error){status.textContent=error.message;}finally{lock(false);}};
 picker.onchange=()=>{if(!targetId)read.onclick();};
 if(initialFile&&!targetId)read.onclick();
 function showReview(){
  const reviewFields=Object.fromEntries(Object.entries(fields[kind]).filter(([k])=>kind!=='payroll'||!['pct','commission','tax_breakdown','job_start','job_end'].includes(k)));
  status.textContent=rows.length+' candidate transactions found. Check the count against your document and review every value before saving.';
  preview.replaceChildren();const note=e('p','Use Add missing row if extraction missed a transaction. Uncheck continuation pages or non-transaction content. Amounts are USD; verify dates and totals.');preview.append(note);
  const wrap=e('div'),table=e('table'),head=e('tr');wrap.className='table-wrap';for(const title of ['Include','Source',...Object.keys(reviewFields),'Review note'])head.append(e('th',title.replaceAll('_',' ')));table.append(head);wrap.append(table);preview.append(wrap);const editors=[];
  function add(row){const tr=e('tr'),include=e('input');include.type='checkbox';const duplicate=kind==='invoices'&&existingRecords.some(r=>r.kind===kind&&String(r.data.invoice_number).trim().toLowerCase()===String(row.data.invoice_number).trim().toLowerCase());include.checked=!duplicate;include.setAttribute('aria-label','Include '+row.source);const td=e('td');td.append(include);tr.append(td,e('td',row.source));const controls={};for(const [key,type] of Object.entries(reviewFields)){const cell=e('td'),control=e(Array.isArray(type)?'select':'input');if(Array.isArray(type)){for(const v of type){const o=e('option',v);o.value=v;control.append(o);}}else{control.type=type;if(type==='number'){control.min='0';control.step='.01';}}control.value=row.data[key]??'';control.setAttribute('aria-label',key+' '+row.source);if(['date','month','invoice_number','amount'].includes(key))control.required=true;controls[key]=control;cell.append(control);tr.append(cell);}tr.append(e('td',duplicate?'Duplicate invoice number — already recorded; excluded.':row.warning));table.append(tr);editors.push({include,controls,source:row.source,original:row.data});}
  rows.forEach(add);const missing=e('button','Add missing row'),save=e('button','Import selected transactions');save.className='primary';preview.append(missing,save);missing.onclick=()=>{if(editors.length>=100){status.textContent='Maximum 100 rows.';return;}add({data:Object.fromEntries(Object.entries(fields[kind]).map(([k,t])=>[k,Array.isArray(t)?t[0]:''])),source:'Manual review '+(editors.length+1),warning:'Added during review'});};
  save.onclick=async()=>{if(busy)return;const selected=[];for(const row of editors){if(!row.include.checked)continue;for(const control of Object.values(row.controls)){if(!control.reportValidity()){status.textContent='Complete required values in '+row.source;return;}}selected.push({data:{...row.original,...Object.fromEntries(Object.entries(row.controls).map(([k,v])=>[k,v.value]))},source:row.source});}if(!selected.length){status.textContent='Select at least one transaction.';return;}lock(true);save.disabled=missing.disabled=true;for(const row of editors){row.include.disabled=true;Object.values(row.controls).forEach(c=>c.disabled=true);}try{await saved(await send(selected));}catch(error){status.textContent=error.message;save.disabled=missing.disabled=false;for(const row of editors){row.include.disabled=false;Object.values(row.controls).forEach(c=>c.disabled=false);}}finally{lock(false);}};
 }
}
