import assert from 'node:assert/strict';
import {Miniflare} from 'miniflare';
import {initializeAuth,totp,signIn,sessionUser} from './auth.mjs';
import {initializeInvitations,createInvitation,beginEnrollment,acceptInvitation,bootstrapAdmin} from './invitations.mjs';
const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("test")}}',compatibilityDate:'2026-08-06',d1Databases:['DB']});
try {
  const db=await mf.getD1Database('DB');await initializeAuth(db);await initializeInvitations(db);
  const now=1800000000,admin={role:'admin',csrf:'test-csrf'};
  await assert.rejects(createInvitation(db,{role:'write',csrf:'test-csrf'},'test-csrf','a@example.test','read',now));
  await assert.rejects(createInvitation(db,admin,'wrong','a@example.test','read',now));
  await assert.rejects(createInvitation(db,admin,'test-csrf','a@example.test','admin',now));
  const first=await createInvitation(db,admin,'test-csrf','reader@example.test','read',now);
  const second=await createInvitation(db,admin,'test-csrf','reader@example.test','read',now);
  assert.equal(await beginEnrollment(db,first.token,now),null);
  const enrollment=await beginEnrollment(db,second.token,now);assert.match(enrollment.otpauth,/otpauth:\/\/totp\//);
  assert.equal(enrollment.email,'reader@example.test');
  assert.equal(await beginEnrollment(db,second.token,now+86400),null);
  assert.equal(await acceptInvitation(db,second.token,'short','123456',now),false);
  const row=await db.prepare('SELECT * FROM poc_invitations WHERE email=?').bind(second.email).first();
  assert.notEqual(row.token_hash,second.token);
  const code=await totp(row.mfa_hex,Math.floor(now/30));
  assert.equal(await acceptInvitation(db,second.token,'Strong test password 123!',code,now),true);
  assert.equal(await acceptInvitation(db,second.token,'Strong test password 123!',code,now),false);
  assert.equal(await beginEnrollment(db,second.token,now),null);
  assert.equal(await signIn(db,second.email,'Strong test password 123!',code,now),null);
  const login=await signIn(db,second.email,'Strong test password 123!',await totp(row.mfa_hex,Math.floor(now/30)+1),now+30);
  assert.equal((await sessionUser(db,login.token,now+30)).role,'read');
  const blocked=await createInvitation(db,admin,'test-csrf','blocked@example.test','write',now);
  for(let i=0;i<10;i++)assert.equal(await acceptInvitation(db,blocked.token,'bad','bad',now),false);
  assert.equal(await beginEnrollment(db,blocked.token,now),null);
  const bootstrap=await bootstrapAdmin(db,now);assert.equal(bootstrap.email,'vamsi@datafoldit.com');
  assert.equal(await acceptInvitation(db,bootstrap.token,'Strong test password 123!','',now,true),false,'Admin may not skip MFA');
  const optional=await createInvitation(db,admin,'test-csrf','optional@example.test','read',now);
  assert.equal(await acceptInvitation(db,optional.token,'Strong test password 123!','',now,true),true);
  const optionalLogin=await signIn(db,optional.email,'Strong test password 123!','',now);
  assert.ok(optionalLogin,'Employee who skipped MFA can sign in with password');
  assert.equal((await sessionUser(db,optionalLogin.token,now)).role,'read');
  console.log('PASS: admin-only invitations, hashed tokens, resend invalidation, expiry, MFA enrollment, one-time acceptance, role preservation and attempt lockout.');
} finally {await mf.dispose();}
