import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {dashboardPage,dashboardJs,fields} from './dashboard.mjs';
const script=process.env.HOSTED_CHECK==='1'?await(await fetch('https://datafoldit-test-poc.vamsibh07.workers.dev/dashboard.js')).text():dashboardJs;
for(const kind of Object.keys(fields)){
 const rows=['a','b'].map((id,i)=>({id,kind,version:1,updated_by:'Sample',data:{...Object.fromEntries(Object.entries(fields[kind]).map(([key,type])=>[key,Array.isArray(type)?type[0]:type==='number'?10:'Sample'])),date:'2026-09-0'+(i+1),month:'2026-09',amount:i?20:100}}));
 const dom=new JSDOM(dashboardPage({email:'sample@example.test',role:'write',csrf:'test'}),{url:'https://test/#'+kind,runScripts:'outside-only'}),w=dom.window;w.scrollTo=()=>{};w.fetch=async path=>({ok:true,json:async()=>path==='/api/records'?rows:[]});
 try{w.eval(script);await new Promise(r=>setTimeout(r,20));assert.equal(w.document.querySelector('#message').textContent,'');assert.equal([...w.document.querySelectorAll('button')].some(b=>b.textContent.startsWith('+ Add')),false);const add=w.document.querySelector('.ledger-heading button');assert.ok(add);add.click();assert.ok(w.document.querySelector('.invoice-draft'));assert.ok(w.document.querySelector('.invoice-draft input[type=file]'));const toggle=w.document.querySelector('.ledger-heading button');assert.equal(toggle.getAttribute('aria-expanded'),'true');toggle.click();assert.equal(w.document.querySelector('.invoice-draft'),null);
 const sort=w.document.querySelector('.sort-column');sort.click();assert.ok(w.document.querySelector('th[aria-sort="ascending"]'));assert.equal(w.document.querySelector('.column-filters'),null);const key=kind==='payroll'?'month':'date';w.document.querySelector('.column-filter-trigger[data-column="'+key+'"]').click();const popup=w.document.querySelector('body>.column-filter-popup'),filter=popup.querySelector('input');assert.ok(popup);for(const c of popup.querySelectorAll('input[type=checkbox]'))c.checked=kind!=='payroll'&&c.value==='2026-09-01';popup.querySelector('button.primary').click();assert.ok(w.document.querySelector('.column-filter-trigger[data-column="'+key+'"].filter-active'));const metric=w.document.querySelector('.ledger-metrics');assert.ok(metric.textContent.includes(kind==='payroll'?'0 matching':'1 matching'));assert.equal(w.document.querySelector('#message').textContent,'');w.document.querySelector('.column-filter-trigger[data-column="'+key+'"]').click();[...w.document.querySelector('body>.column-filter-popup').querySelectorAll('button')].find(b=>b.textContent==='Clear filter').click();assert.ok(w.document.querySelector('.ledger-metrics').textContent.includes('2 matching'));assert.equal(w.document.querySelector('.filter-active'),null);
 }finally{w.close();}
}
console.log('PASS: complete client renders all four ledgers, inline attachments, add/cancel toggle, clickable sorting and column filters');
