-- Synthetic test fixtures only. Stable IDs preserve existing records on reruns.
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-01','bank','{"date":"2026-08-01","type":"Opening","category":"Opening balance","detail":"SAMPLE opening balance","source":"Sample operating account","amount":25000}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-02','bank','{"date":"2026-08-20","type":"Deposit","category":"Client payment","detail":"SAMPLE invoice payment","source":"Sample Acme","amount":12000}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-03','bank','{"date":"2026-08-25","type":"Expense","category":"Software","detail":"SAMPLE software subscription","source":"Sample Cloud Tools","amount":450}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-04','bank','{"date":"2026-08-31","type":"Withdrawal","category":"Payroll","detail":"SAMPLE payroll payout","source":"Sample payroll","amount":10500}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-05','bank','{"date":"2026-09-02","type":"Expense","category":"Office","detail":"SAMPLE office rent","source":"Sample Workspace","amount":1800}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-06','expenses','{"date":"2026-08-25","category":"Software","vendor":"SAMPLE Cloud Tools","description":"SAMPLE monthly subscription","amount":450,"paid_by":"Sample company account","frequency":"Monthly"}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-07','expenses','{"date":"2026-09-02","category":"Office","vendor":"SAMPLE Workspace","description":"SAMPLE office rent","amount":1800,"paid_by":"Sample company account","frequency":"Monthly"}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-08','expenses','{"date":"2026-09-04","category":"Travel","vendor":"SAMPLE Travel Co","description":"SAMPLE client visit","amount":325,"paid_by":"Sample employee","frequency":"One-time"}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-09','expenses','{"date":"2026-09-06","category":"Equipment","vendor":"SAMPLE Tech Store","description":"SAMPLE monitor","amount":275,"paid_by":"Sample company account","frequency":"One-time"}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-10','payroll','{"month":"2026-08","first_name":"SAMPLE Alex","last_name":"River","vendor":"Sample Staffing","client":"Sample Acme","vendor_pay":50,"hours":160,"gross":8000,"tax":1600,"commission":800,"employee_pay":5600,"credit_date":"2026-08-31","paystub_sent":"Y"}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-11','payroll','{"month":"2026-08","first_name":"SAMPLE Jamie","last_name":"Lake","vendor":"Sample Staffing","client":"Sample Northstar","vendor_pay":43.75,"hours":160,"gross":7000,"tax":1400,"commission":700,"employee_pay":4900,"credit_date":"2026-08-31","paystub_sent":"Y"}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-12','payroll','{"month":"2026-09","first_name":"SAMPLE Morgan","last_name":"Vale","vendor":"Sample Staffing","client":"Sample Acme","vendor_pay":50,"hours":80,"gross":4000,"tax":800,"commission":400,"employee_pay":2800,"credit_date":"","paystub_sent":"N"}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-13','invoices','{"date":"2026-08-01","received_date":"2026-08-20","invoice_number":"SAMPLE-1001","customer":"SAMPLE Acme","due_date":"2026-08-31","amount":12000,"status":"Paid","balance_due":0,"commission_amount":3600}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-14','invoices','{"date":"2026-08-05","received_date":"2026-08-06","invoice_number":"SAMPLE-1002","customer":"SAMPLE Northstar","due_date":"2026-09-01","amount":8000,"status":"Open","balance_due":8000,"commission_amount":2400}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-15','invoices','{"date":"2026-09-01","received_date":"2026-09-02","invoice_number":"SAMPLE-1003","customer":"SAMPLE Harbor","due_date":"2026-09-30","amount":6000,"status":"Open","balance_due":3500,"commission_amount":1800}','Sample data') ON CONFLICT(id) DO NOTHING;
INSERT INTO dashboard_records(id,kind,data,updated_by) VALUES ('sample-20260908-16','invoices','{"date":"2026-08-15","received_date":"","invoice_number":"SAMPLE-1004","customer":"SAMPLE Acme","due_date":"2026-09-15","amount":2500,"status":"VOID","balance_due":0,"commission_amount":0}','Sample data') ON CONFLICT(id) DO NOTHING;
