import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {dashboardPage,dashboardJs,fields} from './dashboard.mjs';
const script=process.env.HOSTED_CHECK==='1'?await(await fetch('https://datafoldit-test-poc.vamsibh07.workers.dev/dashboard.js')).text():dashboardJs;
for(const kind of Object.keys(fields)){
 const key=kind==='bank'?'source':kind==='invoices'?'customer':'vendor';const records=['Alpha','Alphabet','Beta',''].map((value,i)=>({id:String(i),kind,updated_by:'Sample',data:{date:'2026-09-09',month:'2026-09',amount:i*10,[key]:value}}));
 const dom=new JSDOM(dashboardPage({email:'sample@example.test',role:'read',csrf:'test'}),{url:'https://test/#'+kind,runScripts:'outside-only'}),w=dom.window;w.scrollTo=()=>{};w.fetch=async path=>({ok:true,json:async()=>path==='/api/records'?records:[]});
 try{w.eval(script);await new Promise(r=>setTimeout(r,25));const open=()=>{w.document.querySelector('.column-filter-trigger[data-column="'+key+'"]').click();return w.document.querySelector('body>.value-filter-popup');};let popup=open();let checks=[...popup.querySelectorAll('input[type=checkbox]')];assert.equal(checks.length,4);const toggle=popup.querySelector('.filter-selection-actions button');assert.equal(toggle.textContent,'Deselect all');toggle.click();assert.ok(checks.every(c=>!c.checked));assert.equal(toggle.textContent,'Select all');toggle.click();assert.ok(checks.every(c=>c.checked));assert.equal(toggle.textContent,'Deselect all');checks[0].checked=false;checks[0].dispatchEvent(new w.Event('change'));assert.equal(toggle.textContent,'Select all');toggle.click();assert.ok(checks.every(c=>c.checked));assert.ok(popup.textContent.includes('(Blank)'));checks.forEach(c=>c.checked=['Alpha',''].includes(c.value));popup.querySelector('.primary').click();assert.ok(w.document.querySelector('.ledger-metrics').textContent.includes('2 matching'),'exact matching excludes Alphabet');
 popup=open();assert.deepEqual([...popup.querySelectorAll('input[type=checkbox]:checked')].map(c=>c.value).sort(),['','Alpha']);const search=popup.querySelector('input[type=search]');search.value='Beta';search.dispatchEvent(new w.Event('input'));assert.equal([...popup.querySelectorAll('.filter-values label')].filter(l=>!l.hidden).length,1);assert.equal(popup.querySelectorAll('input[type=checkbox]:checked').length,2,'search does not change chosen values');
 [...popup.querySelectorAll('button')].find(b=>b.textContent==='Clear filter').click();assert.ok(w.document.querySelector('.ledger-metrics').textContent.includes('4 matching'));
 w.document.querySelector('.columns-button').click();popup=w.document.querySelector('body>.columns-popup');[...popup.querySelectorAll('button')].find(b=>b.textContent==='Deselect all').click();assert.equal(popup.querySelectorAll('input:checked').length,1);assert.ok(popup.querySelector('input:disabled').checked);[...popup.querySelectorAll('button')].find(b=>b.textContent==='Select all').click();assert.equal(popup.querySelectorAll('input:not(:checked)').length,0);
 }finally{w.close();}
}
console.log('PASS: existing-value multi-select, exact matching, blanks, find-value search, saved selection, clear filter and Columns select/deselect all with locked ID');
